#!/bin/bash

PLUGIN_DIR="$CONFIG_DIR/plugins"

# Load colors
source "$CONFIG_DIR/colors.sh"

##### Bar Appearance #####
sketchybar --bar position=top height=36 blur_radius=30 color=$BAR_COLOR topmost=on

##### Changing Defaults #####
default=(
  padding_left=0
  padding_right=0
  icon.font="Hack Nerd Font:Regular:14.0"
  label.font="SF Pro:Semibold:14.0"
  icon.color=$DEFAULT_ICON_COLOR
  label.color=$DEFAULT_LABEL_COLOR
  icon.padding_left=10
  icon.padding_right=10
  label.padding_left=0
  label.padding_right=10
  background.padding_left=4
  background.padding_right=4
)
sketchybar --default "${default[@]}"

sketchybar --add event aerospace_workspace_change
sketchybar --add event aerospace_mode_changed

for sid in $(aerospace list-workspaces --all); do
  # Map workspace names to short display icons
  space_icon=""
  case "$sid" in
  *rowsing) space_icon="B" ;;
  *ommunication) space_icon="C" ;;
  *evelopment) space_icon="D" ;;
  *xtra) space_icon="E" ;;
  *ile_Management) space_icon="F" ;;
  *aming) space_icon="G" ;;
  *usic) space_icon="M" ;;
  *ther) space_icon="O" ;;
  *lanning) space_icon="P" ;;
  *esearch) space_icon="R" ;;
  *ystem_Administration) space_icon="S" ;;
  *riting) space_icon="W" ;;
  *ooling) space_icon="T" ;;
  *VM | *M) space_icon="V" ;;
  *ject_*1*) space_icon="1" ;;
  *ject_*2*) space_icon="2" ;;
  *ject_*3*) space_icon="3" ;;
  *ject_*4*) space_icon="4" ;;
  *) space_icon="$sid" ;;
  esac

  sketchybar --add item space.$sid left \
    --subscribe space.$sid aerospace_workspace_change \
    --set space.$sid \
    background.color=$TRANSPARENT \
    background.corner_radius=5 \
    background.height=25 \
    background.drawing=off \
    background.padding_left=6 \
    background.padding_right=6 \
    y_offset=1 \
    icon="$space_icon" \
    icon.font="SF Pro:Bold:16.0" \
    icon.highlight_color=$SPACE_HIGHLIGHT_COLOR \
    label.drawing=off \
    label.font="sketchybar-app-font:Regular:14.0" \
    label.y_offset=-1 \
    click_script="aerospace workspace $sid" \
    script="$CONFIG_DIR/plugins/aerospace.sh $sid"
done

##### Adding Left Items #####
sketchybar --add item chevron left \
  --set chevron icon= label.drawing=off \
  --add item front_app left \
  --set front_app icon.drawing=off label.drawing=on script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app front_app_switched \
  --add item front_app_layout left \
  --set front_app_layout \
  icon.drawing=on \
  icon.font="Hack Nerd Font:Regular:11.0" \
  icon.color=$FRONT_APP_LAYOUT_ICON_COLOR \
  icon.padding_left=6 \
  icon.padding_right=6 \
  label.drawing=off \
  background.drawing=on \
  background.color=$FRONT_APP_LAYOUT_BG_COLOR \
  background.corner_radius=4 \
  background.height=16 \
  script="$PLUGIN_DIR/front_app.sh" \
  --subscribe front_app_layout front_app_switched aerospace_mode_changed

##### Adding Right Items #####
sketchybar --add item clock right \
  --set clock update_freq=10 icon= script="$PLUGIN_DIR/clock.sh" \
  --add item battery right \
  --set battery update_freq=120 icon.drawing=on icon.font="Hack Nerd Font:Regular:14.0" script="$PLUGIN_DIR/battery.sh" \
  --subscribe battery system_woke power_source_change \
  --add item calendar_event right \
  --set calendar_event \
  update_freq=60 \
  script="$PLUGIN_DIR/calendar_event.sh" \
  click_script="open -a Calendar" \
  icon.font="Hack Nerd Font:Regular:14.0" \
  label.color="$CAL_EVENT_LABEL_COLOR" \
  background.drawing=on \
  background.color="$CAL_EVENT_BG_COLOR" \
  background.corner_radius=8 \
  background.height=25

# --add item things_todo right \
# --set things_todo update_freq=60 \
# script="$PLUGIN_DIR/things_todo.sh" \
# click_script="open -a Things3" \
# background.drawing=on \
# background.color=$GREY_TRANSP \
# background.corner_radius=8 \
# background.height=25

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
